In [1]:
import numpy as np

In [2]:
student=np.array([10,20,30,40,50])

In [3]:
student

array([10, 20, 30, 40, 50])

In [4]:
print("Student number of", student[2])

Student number of 30


In [5]:
std = [11,12,13,14,15]
std = np.array(std)

In [6]:
std

array([11, 12, 13, 14, 15])

In [7]:
std1 = np.arange(40,56)

In [8]:
std1

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55])

In [9]:
std1.reshape(4,4)

array([[40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55]])

In [10]:
std.reshape(2,8)

ValueError: cannot reshape array of size 5 into shape (2,8)

In [11]:
std1.reshape(2,8)

array([[40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [20]:
arr1 = np.array([[2,3,4], [5,8,9]])

In [21]:
arr1

array([[2, 3, 4],
       [5, 8, 9]])

In [22]:
arr2 = np.array([[19,45,98],[54,32,12]])

In [23]:
arr1 + arr2

array([[ 21,  48, 102],
       [ 59,  40,  21]])

In [24]:
subjects = np.array(["JAVA", "react", "node", "php", "python"])

In [25]:
subjects

array(['JAVA', 'react', 'node', 'php', 'python'], dtype='<U6')

In [26]:
subjects[2:4]

array(['node', 'php'], dtype='<U6')

In [27]:
array2 = np.ones([3,3])

In [28]:
array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])